# SPDX-FileCopyrightText: © Sebastian Thomschke and contributors
# SPDX-FileContributor: Sebastian Thomschke (https://sebthom.de)
# SPDX-License-Identifier: EPL-2.0
# SPDX-ArtifactOfProjectHomePage: https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin
#
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
name: Build

on:
  push:
    branches-ignore:  # build all branches except:
    - "dependabot/**"  # prevent GHA triggered twice (once for commit to the branch and once for opening/syncing the PR)
    tags-ignore:  # don't build tags
    - "**"
    paths-ignore:
    - ".act*"
    - "**/*.adoc"
    - "**/*.md"
    - ".editorconfig"
    - ".git*"
    - ".github/*.yml"
    - ".github/ISSUE_TEMPLATE/*"
    - ".github/workflows/stale.yml"
  pull_request:
    paths-ignore:
    - ".act*"
    - "**/*.adoc"
    - "**/*.md"
    - ".editorconfig"
    - ".git*"
    - ".github/*.yml"
    - ".github/ISSUE_TEMPLATE/*"
    - ".github/workflows/stale.yml"
  workflow_dispatch:
    # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
    inputs:
      extra-maven-args:
        description: "Additional command-line arguments to append to all Maven invocations"
        required: false
        type: string
      debug-with-ssh:
        description: "Start an SSH session for debugging purposes at the end of the build:"
        default: never
        type: choice
        options: [ always, on_failure, on_failure_or_cancelled, never ]
      debug-with-ssh-only-for-actor:
        description: "Restrict SSH debug session access to the GitHub user who triggered the workflow"
        default: true
        type: boolean


jobs:
  ###########################################################
  eclipse-plugin-build:
  ###########################################################
    uses: sebthom/gha-shared/.github/workflows/reusable.eclipse-plugin-build.yml@v1
    with:
      timeout-minutes: 10

      target-files: build.target

      extra-maven-args: ${{ inputs.extra-maven-args }}
      jarsigner-alias: sebthom.github.io

      development-branch: none
      development-updatesite-branch: updatesite-preview
      release-branch: main
      release-updatesite-branch: updatesite
      release-archive-name: de.sebthom.eclipse.extra_syntax_highlighting.updatesite.zip

      debug-with-ssh: ${{ inputs.debug-with-ssh }}
      debug-with-ssh-only-for-actor: ${{ inputs.debug-with-ssh-only-for-actor }}

    secrets:
      JARSIGNER_KEYSTORE: ${{ secrets.CERTDB }}  # populated by https://github.com/sebthom/sebthom.github.io/actions/workflows/renew-cert.yml

    permissions:
      actions: write        # to delete action cache entries
      contents: write       # to create releases (commit to updatesite branches)
      pull-requests: write  # for dependabot auto merges
